# Generated by Django 2.0 on 2018-05-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_user_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
